name = "aoc2024"
version = "0.1.0"
defaultTargets = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17"]

[[lean_lib]]
name = "Aoc2024"

[[lean_exe]]
name = "01"
root = "Day01"

[[lean_exe]]
name = "02"
root = "Day02"

[[lean_exe]]
name = "03"
root = "Day03"

[[lean_exe]]
name = "04"
root = "Day04"

[[lean_exe]]
name = "05"
root = "Day05"

[[lean_exe]]
name = "06"
root = "Day06"

[[lean_exe]]
name = "07"
root = "Day07"

[[lean_exe]]
name = "08"
root = "Day08"

[[lean_exe]]
name = "09"
root = "Day09"

[[lean_exe]]
name = "10"
root = "Day10"

[[lean_exe]]
name = "11"
root = "Day11"

[[lean_exe]]
name = "12"
root = "Day12"

[[lean_exe]]
name = "13"
root = "Day13"

[[lean_exe]]
name = "14"
root = "Day14"

[[lean_exe]]
name = "15"
root = "Day15"

[[lean_exe]]
name = "16"
root = "Day16"

[[lean_exe]]
name = "17"
root = "Day17"
