name = "aoc2024"
version = "0.1.0"
defaultTargets = ["01", "02"]

[[lean_lib]]
name = "Aoc2024"

[[lean_exe]]
name = "01"
root = "Day01"

[[lean_exe]]
name = "02"
root = "Day02"

[[lean_exe]]
name = "03"
root = "Day03"

[[lean_exe]]
name = "04"
root = "Day04"

[[lean_exe]]
name = "05"
root = "Day05"
